// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dwejnmcdvldbaqzltidt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR3ZWpubWNkdmxkYmFxemx0aWR0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExMzk2MTYsImV4cCI6MjA2NjcxNTYxNn0.qNtS4Xu_W2Ss3IqPRnYoyWJzmyxl9laajKFCNyOyvhQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);